### ISSUE TITLE
All tabs are refreshed, blocking browser and data lost

### ISSUE THREAD

**Issue by tatankat** [igorlogius/dontLoadImages#1]
Hi,
Thanks for your extension of ImageBlock. A blacklist was exactly what I needed (and could not find in other addons).
But, while testing, it refreshed all my tabs. I'm not too sure when it exactly happens as it takes some time to propagate and it looks clear in the code. That has several consequences, including:
- the browser is unusable for several minutes (and longer due to my massive number of tabs) while all my tabs are reloading
- any websites with temporary data and SPA are reset

I think it is ok if you only refresh the current active tab. The downside is that you don't immediately have the effect of the setting in all tabs but the current, but it won't break anything and no data is lost.

**Comment by igorlogius** [comment]
That is a good point.

I indeed did not consider that some tabs could be in an un-refreshable/stable state and that this might cause considerable lag/strain on the browser process and network load. 

I'll check if there is a way to detect if a tab is in such a state and  if not i'll likely  go with your suggestion,
to only refresh the current tab, or maybe leave the refresh action completely to the user and 
 just add a notification hint, to inform the user, to refesh the tabs.  Might be a little annoying, but  
a switch to disable the message on the option page for users who already got familiar with the addon could be added later.  

I'll think a little more about what would be the best solution.
If you have any more inputs,  feel free  to add them here.

Thanks for the very indepth and detailed report.

**Comment by igorlogius** [comment]
Version `1.3.6` has been released on AMO and  fixes the reloading behaviour.
