### ISSUE TITLE
images still displayed

### ISSUE THREAD

**Issue by tatankat** [igorlogius/dontLoadImages#3]
Hi,
Now that I am able to really test the add-on, it looks like whatever I do (black/whitelist, add/remove), images are still shown after I refresh the page.
I did not yet investigate further (it may be something stupid from my side), will do as soon as I have the time.

**Comment by igorlogius** [comment]
Here is a little screen capture of version 1.3.6. 

![capture-1624364883](https://user-images.githubusercontent.com/67047467/122925680-9a0b1d80-d356-11eb-9948-4f91b0ed3e9a.gif)

Would you please share, which pages you used for testing?
The issue might be with your testset.

**Comment by tatankat** [comment]
I tested with wikipedia, dontLoadImages 1.3.6 and FF 85.0.2

I get this message:
`
  URL constructor: undefined is not a valid URL.
   onBeforeRequest moz-extension://e0252262-1381-4219-9762-99e50e225fc4/background.js:36
`

`tab.url` is undefined, although `tab` is an object.
`details.documentUrl` like it was before has the value `https://www.wikipedia.org/`

The cause is probably because the "tabs" permission has been removed. Maybe `details.documentUrl` should still be used instead, but probably you also had a reason to change it.

**Comment by igorlogius** [comment]
My bad, i was experimenting with the  permissions a bit and  that lead to using the  `documentUrl`.

But  i think the documentUrl ... might in some cases  with embeded documents not always  be correct so i opted to use the other medhtod. 

My blunder should  fixed in `1.3.7`. 
Sorry for the trouble.

**Comment by tatankat** [comment]
No problem. Thanks, it works now!
